version: '2'
services:
    nodejsTest:
        image: 'nodejs-test:latest'
        container_name: nodejs-test
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./
        ports:
            - '3000:3000'
        volumes:
            - './data/logs:/opt/nodejs-test/logs'